using System;

namespace TableTranslator.Model.ColumnConfigurations
{
    public sealed class GuidIdentityColumnConfiguration : IdentityColumnConfiguration
    {
        public GuidIdentityColumnConfiguration()
        {
        }

        public GuidIdentityColumnConfiguration(string columnName) : base(columnName)
        {
        }

        protected internal override Type DataType => typeof(Guid);

        internal override bool IsAutoGenerated => false;

        protected internal override object GetValue(object previousValue) => Guid.NewGuid();
    }
}