using System;

namespace TableTranslator.Model.Settings
{
    public sealed class GuidIdentitySettings : IdentitySettings
    {
        public GuidIdentitySettings()
        {
        }

        public GuidIdentitySettings(string columnName) : base(columnName)
        {
        }

        protected internal override Type Type => typeof(Guid);

        protected internal override bool IsAutoGenerated => false;

        protected internal override object GetValue(object previousValue)
        {
            return Guid.NewGuid();
        }
    }
}