using System;
using System.Data;
using TableTranslator.Exceptions;

namespace TableTranslator.Model.Settings
{
    public sealed class IntIdentitySettings : IdentitySettings
    {
        private int IdentityIncrement { get; set; }
        private int IdentitySeed { get; set; }

        public IntIdentitySettings(int identityIncrement = 1, int identitySeed = 1)
            : base(string.Empty)
        {
            this.IdentityIncrement = identityIncrement;
            this.IdentitySeed = identitySeed;
        }

        public IntIdentitySettings(string columnName, int identityIncrement = 1, int identitySeed = 1) : base(columnName)
        {
            this.IdentityIncrement = identityIncrement;
            this.IdentitySeed = identitySeed;
        }

        protected internal override Type Type => typeof(int);

        protected internal override bool IsAutoGenerated => true;

        protected internal override DataColumn GenerateIdentityColumn()
        {
            var column = base.GenerateIdentityColumn();
            column.AutoIncrement = true;
            column.AutoIncrementSeed = this.IdentitySeed;
            column.AutoIncrementStep = this.IdentityIncrement;
            return column;
        }

        protected internal override object GetValue(object previousValue)
        {
            throw new TableTranslatorConfigurationException("Identity column is auto generated by the data table.");
        }
    }
}