using System;
using System.Data;

namespace TableTranslator.Model.ColumnConfigurations.Identity
{
    /// <summary>
    /// Base class for identity column configurations
    /// </summary>
    public abstract class IdentityColumnConfiguration : BaseColumnConfiguration
    {
        internal bool IsAutoGenerated { get; set; }
        private Type _type;
        private string _providedColumnName { get; set; }

        internal IdentityColumnConfiguration(Type type)
        {
            Init(type, null);
        }

        internal IdentityColumnConfiguration(Type type, string columnName)
        {
            Init(type, columnName);
        }

        private void Init(Type type, string columnName)
        {
            this._type = type;
            this._providedColumnName = columnName;
        }

        /// <summary>
        /// Name of the column
        /// </summary>
        public sealed override string ColumnName => !string.IsNullOrWhiteSpace(this._providedColumnName)
            ? this._providedColumnName
            : base.OrdinalColumnName;

        /// <summary>
        /// Data type of the column
        /// </summary>
        public sealed override Type ColumnDataType => this._type;

        /// <summary>
        /// Returns the next value for the identity
        /// </summary>
        /// <param name="previousValue"></param>
        /// <returns>Value of the identity data column for the next row</returns>
        protected internal abstract object GetNextValue(object previousValue);

        /// <summary>
        /// Generates the identity data column
        /// </summary>
        /// <returns>Identity data column</returns>
        protected internal virtual DataColumn GenerateIdentityColumn() =>
            new DataColumn(this.ColumnName, this.ColumnDataType)
            {
                Unique = true
            };
    }
}