using System;
using System.Data;

namespace TableTranslator.Model.ColumnConfigurations.Identity
{
    /// <summary>
    /// Base class for identity column configurations
    /// </summary>
    public abstract class IdentityColumnConfiguration : BaseColumnConfiguration
    {
        private Type _type;
        protected internal bool IsAutoGenerated { get; set; }
        private string _providedColumnName { get; set; }

        protected internal IdentityColumnConfiguration(Type type)
        {
            Init(type, null);
        }

        protected internal IdentityColumnConfiguration(Type type, string columnName)
        {
            Init(type, columnName);
        }

        private void Init(Type type, string columnName)
        {
            this._type = type;
            this._providedColumnName = columnName;
        }

        public string ColumnName => !string.IsNullOrWhiteSpace(this._providedColumnName)
            ? this._providedColumnName
            : base.OrdinalColumnName;

        public override Type ColumnDataType => this._type;

        protected internal virtual DataColumn GenerateIdentityColumn() => 
            new DataColumn(this.ColumnName, this.ColumnDataType)
            {
                Unique = true
            };

        protected internal abstract object GetValue(object previousValue);
    }
}