using System;
using System.Data;

namespace TableTranslator.Model.ColumnConfigurations.Identity
{
    public abstract class IdentityColumnConfiguration : BaseColumnConfiguration
    {
        private string _providedColumnName { get; set; }
        public Type DataType { get; private set; }
        protected internal bool IsAutoGenerated { get; set; }

        protected IdentityColumnConfiguration(Type type)
        {
            Init(type, null);
        }

        protected IdentityColumnConfiguration(Type type, string columnName)
        {
            Init(type, columnName);
        }

        private void Init(Type type, string columnName)
        {
            this.DataType = type;
            this._providedColumnName = columnName;
        }

        public string ColumnName => !string.IsNullOrWhiteSpace(this._providedColumnName)
            ? this._providedColumnName
            : base.OrdinalColumnName;

        protected internal virtual DataColumn GenerateIdentityColumn() => 
            new DataColumn(this.ColumnName, this.DataType)
            {
                Unique = true
            };

        protected internal abstract object GetValue(object previousValue);
    }
}